[package]
name = "twpw"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
colored = "2.0.0"
chrono = "0.4"
crossterm = "0.23.2"
getch = "0.3.1"
#i_o = { path = "../i_o" }
